{% set name = "phylorank" %}
{% set version = "0.1.7" %}
{% set sha256 = "84957fae8f2529ac8f46620d1d8db24ee59be4382f781f86dd3c015880d4d9e6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vvv
  entry_points:
    - phylorank = phylorank.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - matplotlib-base
    - jinja2 >=2.7.3
    - dendropy >=4.1.0
    - biolib >=0.1.0
    - scipy
    - mpld3 >=0.2

test:
  imports:
    - phylorank
    - phylorank.plot
  commands:
    - phylorank -h

about:
  home: https://github.com/dparks1134/PhyloRank
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: LICENSE
  summary: |
    PhyloRank provides functionality for calculating the relative evolutionary
    divergence (RED) of taxa in a tree and for finding the best placement of
    taxonomic labels in a tree.
